client_id = "1bd9623cc54e833a0a0aec96a5fe1af4"
name = "Sticky Add-To-Cart Bar Pro"
application_url = "https://sticky-add-to-cart-bar-pro.onrender.com"
embedded = true

[build]
dev_store_url = "bdm-sandbox.myshopify.com"

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact"
]
uri = "/webhooks"

[access_scopes]
scopes = "read_orders,read_products,write_script_tags,read_themes"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://sticky-add-to-cart-bar-pro.onrender.com/auth/callback"
]

[app_proxy]
url = "https://sticky-add-to-cart-bar-pro.onrender.com"
subpath = "bdm-sticky-atc"
prefix = "apps"

[[extensions]]
type = "theme"
handle = "sticky-atc-bar"
uid = "1ce1ff9d-dec9-257f-dc46-969008c929b71f8a67d2"